name: CI
on:
    pull_request:
        branches:
            - main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build and test
        run: pnpm turbo --color build lint test lint-versions
