name: Publish
on:
    push:
        branches:
            - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
            - name: Set up pnpm
              uses: pnpm/action-setup@v4
            - name: Set up node
              uses: actions/setup-node@v4
              with:
                  node-version-file: package.json
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Build and test
              run: pnpm turbo --color build lint test lint-versions
            - name: Create publish PR
              id: changesets
              uses: changesets/action@v1
              with:
                  publish: pnpm changeset publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}